name: update check
on:
  workflow_dispatch: 

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
    - name: checkout
      uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29 # v4

    - name: Set up Docker Buildx
      id: buildx
      uses: docker/setup-buildx-action@master

    - name: Build
      uses: docker/build-push-action@v5
      with:
        builder: ${{ steps.buildx.outputs.name }}
        context: .
        file: ./Dockerfile
        platforms: linux/amd64
        push: false
        load: true
        tags: seb-openvpn:local
      
    - name: check
      run: |
        docker images
        echo "checking checksum"
        docker inspect --format='{{.RepoDigests}}' seb-openvpn:local
        docker images --digests
